<a href="https://colab.research.google.com/github/sathyapramodks/BytsLinkapp/blob/master/Initial_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import io

In [5]:
from google.colab import files

In [14]:
uploaded = files.upload()

Saving monthlyColorPlan.csv to monthlyColorPlan (2).csv

In [29]:
df = pd.read_csv(io.BytesIO(uploaded['monthlyColorPlan.csv']), encoding='cp1252')

In [30]:
df.head()

,PLANT,MODEL,VARIANT,PART NO,DESCRIPTION,1,2,3,4,5,...,26,27,28,29,30,31,Unnamed: 36,Ceiling Total,Workout Total,Diff
0,HOS,XL 100,XL 100 HD ES BS VI,P71903002H,TVS XL100 HD I-TOUCH START-BS6 AP RED,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0
1,HOS,XL 100,XL 100 HD ES BS VI,P71903000D,TVS XL100 HD I-TOUCH START-BS6 BLACK,170.0,170.0,170.0,0.0,153.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,3094.0,3094.0,0.0
2,HOS,XL 100,XL 100 HD ES BS VI,P71903008B,TVS XL100 HD I-TOUCH START-BS6 DP M.BLUE,45.0,45.0,45.0,0.0,41.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,822.0,819.0,-3.0
3,HOS,XL 100,XL 100 HD ES BS VI,P71903007L,TVS XL100 HD I-TOUCH START-BS6 M.GREEN,175.0,175.0,175.0,0.0,158.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,3188.0,3185.0,-3.0
4,HOS,XL 100,XL 100 HD ES BS VI,P71903005A,TVS XL100 HD I-TOUCH START-BS6 M.PURPLE,75.0,75.0,75.0,0.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1368.0,1365.0,-3.0

In [31]:
df.columns

Index(['PLANT', 'MODEL', 'VARIANT', 'PART NO', 'DESCRIPTION', '1', '2', '3',
       '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16',
       '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28',
       '29', '30', '31', 'Unnamed: 36', 'Ceiling Total', 'Workout Total',
       'Diff'],
      dtype='object')

In [34]:
df.drop(columns = ['PLANT', 'Ceiling Total', 'Workout Total', 'Diff'], inplace = True,axis = 1).head(5)

AttributeError: ignored

In [27]:
df.set_index(['PART NO']).head(5)

,MODEL,VARIANT,DESCRIPTION,1,2,3,4,5,6,7,...,23,24,25,26,27,28,29,30,31,Unnamed: 36
PART NO,,,,,,,,,,,,,,,,,,,,,
P71903002H,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 AP RED,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903000D,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 BLACK,170.0,170.0,170.0,0.0,153.0,136.0,170.0,...,153.0,153.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903008B,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 DP M.BLUE,45.0,45.0,45.0,0.0,41.0,36.0,45.0,...,41.0,41.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903007L,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 M.GREEN,175.0,175.0,175.0,0.0,158.0,140.0,175.0,...,158.0,158.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903005A,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 M.PURPLE,75.0,75.0,75.0,0.0,68.0,60.0,75.0,...,68.0,68.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [36]:
df['MODEL'].value_counts()

XL 100         20
JUPITER 110    20
SPORT          16
CITY+          15
RADEON         14
RAIDER         14
JUPITER 125    10
Name: MODEL, dtype: int64

In [75]:
newdf = df[df['MODEL'] != "XL 100"].dropna(axis = 0, how = "all")
newdf = df[df['MODEL'] != "JUPITER 125"].dropna(axis = 0, how = "all")
newdf = df[df['MODEL'] != "JUPITER 110"].dropna(axis = 0, how = "all")

In [76]:
newdf['MODEL'].value_counts()

XL 100         20
SPORT          16
CITY+          15
RADEON         14
RAIDER         14
JUPITER 125    10
Name: MODEL, dtype: int64

In [77]:
newdf.set_index(["PART NO"], inplace = True)

In [78]:
newdf.head(5)

,MODEL,VARIANT,DESCRIPTION,1,2,3,4,5,6,7,...,23,24,25,26,27,28,29,30,31,Unnamed: 36
PART NO,,,,,,,,,,,,,,,,,,,,,
P71903002H,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 AP RED,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903000D,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 BLACK,170.0,170.0,170.0,0.0,153.0,136.0,170.0,...,153.0,153.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903008B,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 DP M.BLUE,45.0,45.0,45.0,0.0,41.0,36.0,45.0,...,41.0,41.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903007L,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 M.GREEN,175.0,175.0,175.0,0.0,158.0,140.0,175.0,...,158.0,158.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
P71903005A,XL 100,XL 100 HD ES BS VI,TVS XL100 HD I-TOUCH START-BS6 M.PURPLE,75.0,75.0,75.0,0.0,68.0,60.0,75.0,...,68.0,68.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [79]:
findf = newdf.transpose()

In [80]:
findf.head(5)

PART NO,P71903002H,P71903000D,P71903008B,P71903007L,P71903005A,P71903008F,P71903109A,P7190310AC,P71903100D,P71903107L,...,N6191950BR,N61911200D,N61911208F,N6191120AC,N6191120BR,N61912600D,N6191260BR,ND1905300D,ND1905400D,NaN
MODEL,XL 100,XL 100,XL 100,XL 100,XL 100,XL 100,XL 100,XL 100,XL 100,XL 100,...,RAIDER,RAIDER,RAIDER,RAIDER,RAIDER,RAIDER,RAIDER,RADEON,RADEON,NaN
VARIANT,XL 100 HD ES BS VI,XL 100 HD ES BS VI,XL 100 HD ES BS VI,XL 100 HD ES BS VI,XL 100 HD ES BS VI,XL 100 HD ES BS VI,XL 100 HD ES SPL EDN BS VI,XL 100 HD ES SPL EDN BS VI,XL 100 HD ES SPL EDN BS VI,XL 100 HD ES SPL EDN BS VI,...,Raider Keihin,Raider Bosch,Raider Bosch,Raider Bosch,Raider Bosch,Raider SX Dom,Raider SX Dom,Radeon Disc Digi BSVI,Radeon Drum Digi BSVI,NaN
DESCRIPTION,TVS XL100 HD I-TOUCH START-BS6 AP RED,TVS XL100 HD I-TOUCH START-BS6 BLACK,TVS XL100 HD I-TOUCH START-BS6 DP M.BLUE,TVS XL100 HD I-TOUCH START-BS6 M.GREEN,TVS XL100 HD I-TOUCH START-BS6 M.PURPLE,TVS XL100 HD I-TOUCHSTART-BS6 RACING RED,TVS XL100 HD i-TOUCH START - B. BROWN,TVS XL100 HD i-TOUCH START -DELIGHT BLUE,TVS XL100 HD i-TOUCH START -SE BLACK,TVS XL100 HD i-TOUCH START – SE M.GREEN,...,TVS RAIDER-DISC2 125 FIERY YELLOW K,TVS RAIDER-DISC 125 WICKED BLACK,TVS RAIDER-DISC 125 STRIKING RED,TVS RAIDER-DISC 125 BLAZING BLUE,TVS RAIDER-DISC 125 FIERY YELLOW,TVS RAIDER-DISC SX 125 WICKED BLACK,TVS RAIDER-DISC SX 125 FIERY YELLOW,TVS RADEON - BSVI ES DISC DIGI BLACK,TVS RADEON - BSVI ES DRUM DIGI BLACK,FORMULA
1,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
2,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN

In [81]:
findf.drop(['MODEL', 'VARIANT', 'DESCRIPTION'])

PART NO,P71903002H,P71903000D,P71903008B,P71903007L,P71903005A,P71903008F,P71903109A,P7190310AC,P71903100D,P71903107L,...,N6191950BR,N61911200D,N61911208F,N6191120AC,N6191120BR,N61912600D,N6191260BR,ND1905300D,ND1905400D,NaN
1,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
2,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
3,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
5,0.0,153.0,41.0,158.0,68.0,32.0,50.0,180.0,10.0,10.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
6,0.0,136.0,36.0,140.0,60.0,28.0,50.0,180.0,10.0,10.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
7,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
8,0.0,136.0,36.0,140.0,60.0,28.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
9,0.0,153.0,41.0,158.0,68.0,32.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
12,0.0,136.0,36.0,140.0,60.0,28.0,50.0,180.0,10.0,10.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
13,0.0,136.0,36.0,140.0,60.0,28.0,50.0,180.0,10.0,10.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
14,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
15,0.0,136.0,36.0,140.0,60.0,28.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,NaN
16,0.0,136.0,36.0,140.0,60.0,28.0,40.0,144.0,8.0,8.0,...,50.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
17,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,50.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
19,0.0,153.0,41.0,158.0,68.0,32.0,40.0,144.0,8.0,8.0,...,50.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
20,0.0,153.0,41.0,158.0,68.0,32.0,40.0,144.0,8.0,8.0,...,50.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
21,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,50.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
22,0.0,170.0,45.0,175.0,75.0,35.0,40.0,144.0,8.0,8.0,...,51.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
23,0.0,153.0,41.0,158.0,68.0,32.0,40.0,144.0,8.0,8.0,...,51.0,0.0,0.0,0.0,0.0,180.0,120.0,30.0,21.0,NaN
24,0.0,153.0,41.0,158.0,68.0,32.0,40.0,144.0,8.0,8.0,...,51.0,0.0,0.0,0.0,0.0,180.0,120.0,0.0,0.0,NaN
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Unnamed: 36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
findf.describe()

PART NO,P71903002H,P71903000D,P71903008B,P71903007L,P71903005A,P71903008F,P71903109A,P7190310AC,P71903100D,P71903107L,...,N6191950BR,N61911200D,N61911208F,N6191120AC,N6191120BR,N61912600D,N6191260BR,ND1905300D,ND1905400D,NaN
count,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,...,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,1
unique,4.0,7.0,7.0,7.0,7.0,7.0,6.0,6.0,6.0,6.0,...,7.0,4.0,4.0,4.0,4.0,6.0,6.0,5.0,5.0,1
top,0.0,0.0,0.0,0.0,0.0,0.0,40.0,144.0,8.0,8.0,...,56.0,0.0,0.0,0.0,0.0,120.0,80.0,30.0,21.0,FORMULA
freq,31.0,11.0,11.0,11.0,11.0,11.0,16.0,16.0,16.0,16.0,...,13.0,31.0,31.0,31.0,31.0,13.0,13.0,20.0,20.0,1